[phases.setup]
aptPkgs = ["libudev-dev", "python3", "build-essential"]
nixPkgs = ["libudev"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"