[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/app/start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Explicitly define environment variables that should be passed to the container
[variables]
HELIUS_API_KEY = "${HELIUS_API_KEY}" 