[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
nodejs-version = "18"

[nixpacks.setup]
# Skip Python installation for node-gyp
python = "false"

[nixpacks.env]
# Skip building native dependencies for usb package
USB_SKIP_INSTALL = "true"
# Skip optional dependencies
SKIP_OPTIONAL_DEPENDENCIES = "true" 